import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Bg from './bg';  // ✅ Correct import path for bg.js at app/bg.js

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Divij's Portfolio",
  description: "Generated by create next app",
  icons: { icon: '/favicon.ico' },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}>
        {/* Background video component */}
        <Bg />

        {/* Page content */}
        {children}
      </body>
    </html>
  );
}
